// Developer Express Code Central Example:
// How to implement the drag-and-drop capability to re-order rows and drop them onto an external control
// 
// We have implemented GridDragDropManager behavior in the grid extentions library.
// This attached behavior allows you to include the drag and drop support in your
// application more easily than the old approach.
// 
// This description is actual
// only for versions earlier than 12.1.:
// The following example demonstrates how to
// implement the drag-and-drop capability to allow end-users to do the
// following:
// 1. re-order grid rows;
// 2. drag any grid row from a grid and drop it
// onto an external control.
// 
// To accomplish this task, it is necessary to set the
// GridView.AllowDrop property to True and handle its PreviewMouseDown,
// PreviewMouseMove, DragOver, and Drop events as shown in this example.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E1194

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragAndDrop_ReorderAndExternal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
